### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MauriceGit** [jobtalle/SketchBugs#1]
Hello,

awesome project, I love it!
I am currently working on a small browser game and would love to maybe use one of those bugs.
Would it be possible to add a permissive license, such as MIT or ISC?

Thanks,
Regards,
Maurice

**Comment by jobtalle** [comment]
Hi @MauriceGit, I just put a MIT license on the repository. Have fun with it!

**Comment by MauriceGit** [comment]
Thanks!
